name: test_with_cwltool

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, 1.2.1_proposed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_with_cwltool:
    strategy:
      fail-fast: false
      matrix:
        # These are options to be set in CWLTOOL_OPTIONS. Note that for
        # the user-space Docker command, the default value is "docker",
        # but that will fail on most CI envs already running on Docker.
        options:
          - --debug --parallel --user-space-docker-cmd=
          - --debug --parallel --user-space-docker-cmd=udocker

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      
      - name: Setup prerequirements
        run: pip install cwltest cwltool udocker && udocker install
      
      - name: Run tests against the reference runner
        env:
          CWLTOOL_OPTIONS: ${{ matrix.options }}
        run: cwltest --junit-verbose --verbose --tool cwltool --test=conformance_tests.yaml -j$(nproc)
