name: test_with_cwltool

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, 1.2.1_proposed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_with_cwltool:
    strategy:
      fail-fast: false
      matrix:
        # These are sets of options to be added via CWLTOOL_OPTIONS
        options:
          - "--parallel --relax-path-checks"
          - "--parallel --relax-path-checks --user-space-docker-cmd=udocker"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'

      - name: hash the container names
        id: containers
        run: |
          echo  "::set-output name=hash::$(git grep dockerPull -- tests | awk '{ print $NF}' | sort -u | md5sum | awk '{print $1}')"
        shell: bash

      - uses: actions/cache@v3
        with:
          path: .udocker
          key: ${{ steps.containers.outputs.hash }}

      - name: Setup prerequirements
        run: pip install "cwltest>=2.3" pytest-xdist "cwltool>=3.1.20230213100550" udocker && udocker install

      - name: Copy in cwltool-specific configuration for the cwltest pytest plugin
        run: cp "$(python -c 'from cwltool.tests.util import get_data; print(get_data("tests/cwl-conformance/cwltool-conftest.py"))')" conftest.py

      - name: Copy conformance test index to .cwltest.yaml
        run: cp conformance_tests.yaml conformance_tests.cwltest.yaml

      - name: Run tests against the reference runner
        env:
          CWLTOOL_OPTIONS: ${{ matrix.options }}
        run: python -m pytest conformance_tests.cwltest.yaml -n auto -rs