name: test_with_cwltool

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, 1.2.1_proposed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_with_cwltool:
    runs-on: ubuntu-latest
    env:
      CWLTOOL_OPTIONS: "--parallel --relax-path-checks"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'
      
      - name: Setup prerequirements
        run: pip install "cwltest>=2.3" pytest-xdist "cwltool>=3.1.20230213100550"

      - name: Copy in cwltool-specific configuration for the cwltest pytest plugin
        run: cp "$(python -c 'from cwltool.tests.util import get_data; print(get_data("tests/cwl-conformance/cwltool-conftest.py"))')" conftest.py

      - name: Copy conformance test index to .cwltest.yaml
        run: cp conformance_tests.yaml conformance_tests.cwltest.yaml

      - name: Run tests against the reference runner
        run: python -m pytest conformance_tests.cwltest.yaml -n auto -rs
